In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(r"housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [63]:
from sklearn.preprocessing import LabelEncoder

In [64]:
le = LabelEncoder()

In [65]:
df['ocean_proximity'] = le.fit_transform(df['ocean_proximity'])
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3

In [66]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [67]:
median_bedroom = df['total_bedrooms'].median() 
df['total_bedrooms'] = df['total_bedrooms'].fillna(median_bedroom)

In [68]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [69]:
X = df.drop('median_house_value', axis=1)
y = df['median_house_value']
y.head()

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [70]:
X.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,3

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [73]:
from sklearn.tree import DecisionTreeRegressor

# Underfit

In [74]:
dt = DecisionTreeRegressor(max_depth=4, random_state=42)

In [75]:
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=4, random_state=42)

In [76]:
from sklearn.metrics import r2_score

In [77]:
y_train_pred = dt.predict(X_train)
y_test_pred = dt.predict(X_test)

In [78]:
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

In [79]:
r2_train   # Underfit bcz of 0.6025152002702147

0.6025152002702147

In [80]:
r2_test

0.5761008510586485

In [81]:
# gap
r2_train-r2_test

0.026414349211566157

# Overfit

In [82]:
dt_1 = DecisionTreeRegressor(max_depth=None, random_state=42)

In [83]:
dt_1.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [84]:
y_pred_train_n = dt_1.predict(X_train)
y_pred_test_n = dt_1.predict(X_test)

In [85]:
r2_train_n = r2_score(y_train, y_pred_train_n)
r2_test_n = r2_score(y_test, y_pred_test_n)

In [86]:
r2_train_n # Overfit bcz of 1.0

1.0

In [87]:
r2_test_n

0.641807096779449

In [88]:
r2_train_n-r2_test_n

0.358192903220551

# Bestfit

In [89]:
from sklearn.ensemble import RandomForestRegressor

In [90]:
re = RandomForestRegressor(
    n_estimators=100,
    random_state=42)

In [91]:
re.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [92]:
y_train_pred_re = re.predict(X_train)
y_test_pred_re = re.predict(X_test)

In [93]:
r2_train_re = r2_score(y_train, y_train_pred_re)
r2_test_re = r2_score(y_test, y_test_pred_re)

In [94]:
r2_train_re

0.9746205451621606

In [95]:
r2_test_re

0.8074523972118022

In [96]:
r2_train_re-r2_test_re

0.1671681479503584